apiVersion: v1
kind: Service
metadata:
  name: tasklane-backend
  namespace: tasklane
spec:
  type: ClusterIP
  selector:
    app: tasklane-backend
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
