apiVersion: v2
name: tasklane-monitoring
description: Lightweight monitoring stack for Tasklane
type: application
version: 0.1.0

dependencies:
  - name: kube-prometheus-stack
    version: 88.3.0
    repository: https://prometheus-community.github.io/helm-charts
