kube-prometheus-stack:

  alertmanager:
    enabled: false

  prometheus:
    enabled: true

    prometheusSpec:
      replicas: 1
      retention: 3d

      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 250m
          memory: 512Mi

  grafana:
    enabled: true

    replicas: 1

    resources:
      requests:
        cpu: 20m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 384Mi

    persistence:
      enabled: false

    defaultDashboardsEnabled: true

  kubeStateMetrics:
    enabled: true

  nodeExporter:
    enabled: true

  prometheusOperator:
    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
