apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tasklane-netdata
  namespace: argocd

spec:
  project: default

  sources:

    # Netdata Helm chart
    - repoURL: https://netdata.github.io/helmchart/
      chart: netdata
      targetRevision: 3.7.171

      helm:
        valueFiles:
          - $values/monitoring/netdata-values.yaml

    # Our GitOps repository containing the values file
    - repoURL: https://github.com/nkdharanikumar/cloudtriad-tasklane-gitops.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
